""" general settings
syntax on
filetype plugin indent on
set nocompatible
set encoding=utf-8
set mouse=a
set number
set cursorline
set cursorcolumn
set background=dark
set laststatus=2
set colorcolumn=80
set t_Co=256
set expandtab
set tabstop=2
set shiftwidth=2
set hlsearch
set incsearch
set nrformats=
set wildmenu
set wildmode=full
set path+=$HOME/data/sql/**
autocmd FileType py,sql autocmd BufWritePre <buffer> %s/\s\+$//e
nn <F9> mzggg?G`z
set ignorecase
set smartcase
let mapleader = "\<Space>"
