""" general settings

" Enable syntax highlighting
syntax on
" Enable filetype detection, plugins, and indentation rules
filetype plugin indent on
" Disable Vi compatibility mode (use full Vim features)
set nocompatible
" Use UTF-8 as the default encoding
set encoding=utf-8
" Enable mouse support in all modes
set mouse=a
" Show line numbers
set number
" Highlight the current line
set cursorline
" Highlight the current column
set cursorcolumn
" Allow backspace to delete over indentation, end of line, etc.
set backspace=2
" Use dark background colors (helps color schemes adapt)
set background=dark
" Always show the status line (even with a single window)
set laststatus=2
" Enable 256-color support in the terminal
set t_Co=256
" Convert tabs to spaces
set expandtab
" Number of spaces that a <Tab> in the file counts for
set tabstop=2
" Number of spaces used for each step of (auto)indent
set shiftwidth=2
" Use a blank space for vertical split separators (remove visible lines between panes)
set fillchars+=vert:\ 
